apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: karthikkaliki/gatewayserver:v10
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_APPLICATION_NAME
              value: "gatewayserver"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://configserver:8071/"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eurekaserver:8070/eureka/"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  ports:
    - port: 8072
      targetPort: 8072
