apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardsdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
        - name: cardsdb
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "cardsdb"
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
spec:
  selector:
    app: cardsdb
  ports:
    - port: 3306
      targetPort: 3306
