apiVersion: apps/v1
kind: Deployment
metadata:
  name: loansdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - name: loansdb
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "loansdb"
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
spec:
  selector:
    app: loansdb
  ports:
    - port: 3306
      targetPort: 3306
