apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: amqp
    port: {{ .Values.service.port }}
    targetPort: amqp
    protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}